"""Viswall DNS Service Agent (BIND9)."""

from __future__ import annotations

import json
import os
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field


NAMED_CONF_PATH = os.getenv("NAMED_CONF_PATH", "/etc/bind/named.conf.local")
ZONES_DIR = os.getenv("ZONES_DIR", "/var/lib/bind/viswall-zones")
ALLOW_COMMANDS = os.getenv("DNS_AGENT_ALLOW_COMMANDS", "false").lower() == "true"


class DNSRecordPayload(BaseModel):
    name: str
    record_type: str
    content: str
    ttl: int = 3600
    priority: int = 0
    weight: int = 0
    port: int = 0


class DNSZonePayload(BaseModel):
    id: int
    name: str
    zone_type: str
    enabled: bool = True
    is_reverse: bool = False
    serial: int
    refresh: int
    retry: int
    expire: int
    minimum_ttl: int
    master_server_address: str | None = None
    records: List[DNSRecordPayload] = Field(default_factory=list)


class DNSServerConfigPayload(BaseModel):
    server_id: int
    name: str
    listening_addresses: List[str] = Field(default_factory=lambda: ["0.0.0.0", "::"])
    port: int = 53
    is_recursive: bool = True
    is_authoritative: bool = True
    forwarders: List[str] = Field(default_factory=list)
    allow_query: List[str] = Field(default_factory=lambda: ["0.0.0.0/0", "::/0"])
    allow_transfer: List[str] = Field(default_factory=lambda: ["127.0.0.1", "::1"])
    zones: List[DNSZonePayload] = Field(default_factory=list)


class ApplyResult(BaseModel):
    success: bool
    message: str
    updated_at: datetime


class DNSAgent:
    def __init__(self) -> None:
        self.zones_path = Path(ZONES_DIR)
        self.named_conf_path = Path(NAMED_CONF_PATH)
        self.zones_path.mkdir(parents=True, exist_ok=True)

    def _zone_file_path(self, zone: DNSZonePayload) -> Path:
        safe_name = zone.name.replace("/", "_").replace("..", "_")
        return self.zones_path / f"zone-{zone.id}-{safe_name}.db"

    def _record_line(self, record: DNSRecordPayload) -> str:
        base = f"{record.name} {record.ttl} IN {record.record_type}"
        rtype = record.record_type.upper()
        if rtype == "MX":
            return f"{base} {record.priority} {record.content}"
        if rtype == "SRV":
            return f"{base} {record.priority} {record.weight} {record.port} {record.content}"
        return f"{base} {record.content}"

    def _default_soa(self, zone: DNSZonePayload) -> str:
        return (
            f"@ IN SOA ns1.{zone.name}. admin.{zone.name}. (\n"
            f"    {zone.serial} ; serial\n"
            f"    {zone.refresh} ; refresh\n"
            f"    {zone.retry} ; retry\n"
            f"    {zone.expire} ; expire\n"
            f"    {zone.minimum_ttl} ; minimum ttl\n"
            ")"
        )

    def write_zone_file(self, zone: DNSZonePayload) -> Path:
        zone_path = self._zone_file_path(zone)
        lines: List[str] = [f"$TTL {zone.minimum_ttl}"]

        has_soa = any(record.record_type.upper() == "SOA" for record in zone.records)
        if not has_soa:
            lines.append(self._default_soa(zone))

        for record in zone.records:
            lines.append(self._record_line(record))

        zone_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return zone_path

    def write_named_conf(self, payload: DNSServerConfigPayload) -> None:
        zone_blocks: List[str] = []
        for zone in payload.zones:
            if not zone.enabled:
                continue

            if zone.zone_type == "master":
                zone_file = self.write_zone_file(zone)
                block = (
                    f'zone "{zone.name}" {{\n'
                    "    type master;\n"
                    f"    file \"{zone_file}\";\n"
                    "};\n"
                )
            elif zone.zone_type == "slave":
                if not zone.master_server_address:
                    raise ValueError(f"Slave zone {zone.name} missing master_server_address")
                zone_file = self._zone_file_path(zone)
                block = (
                    f'zone "{zone.name}" {{\n'
                    "    type slave;\n"
                    f"    masters {{ {zone.master_server_address}; }};\n"
                    f"    file \"{zone_file}\";\n"
                    "};\n"
                )
            else:
                zone_file = self.write_zone_file(zone)
                block = (
                    f'zone "{zone.name}" {{\n'
                    f"    type {zone.zone_type};\n"
                    f"    file \"{zone_file}\";\n"
                    "};\n"
                )

            zone_blocks.append(block)

        conf = [
            "// Generated by Viswall DNS agent",
            f"// server_id={payload.server_id}",
            f"// generated_at={datetime.utcnow().isoformat()}",
            "",
            "options {",
            f"    recursion {'yes' if payload.is_recursive else 'no'};",
            "    allow-query { " + "; ".join(payload.allow_query) + "; };",
            "    allow-transfer { " + "; ".join(payload.allow_transfer) + "; };",
            "    forwarders { " + "; ".join(payload.forwarders) + (';' if payload.forwarders else '') + " };",
            "};",
            "",
            *zone_blocks,
        ]

        self.named_conf_path.parent.mkdir(parents=True, exist_ok=True)
        self.named_conf_path.write_text("\n".join(conf) + "\n", encoding="utf-8")

    def _run(self, args: List[str]) -> Dict[str, Any]:
        if not ALLOW_COMMANDS:
            return {"skipped": True, "command": args}
        result = subprocess.run(args, capture_output=True, text=True, check=False)
        return {
            "skipped": False,
            "command": args,
            "returncode": result.returncode,
            "stdout": result.stdout,
            "stderr": result.stderr,
        }

    def reload_bind(self) -> Dict[str, Any]:
        return self._run(["rndc", "reload"])

    def bind_status(self) -> Dict[str, Any]:
        return self._run(["rndc", "status"])


agent = DNSAgent()
app = FastAPI(title="Viswall DNS Agent", version="1.0.0")


@app.get("/health")
async def health() -> Dict[str, Any]:
    return {
        "status": "healthy",
        "service": "dns-agent",
        "named_conf": str(agent.named_conf_path),
        "zones_dir": str(agent.zones_path),
        "commands_enabled": ALLOW_COMMANDS,
    }


@app.post("/dns/apply", response_model=ApplyResult)
async def apply_dns_config(payload: DNSServerConfigPayload) -> ApplyResult:
    try:
        agent.write_named_conf(payload)
        reload_result = agent.reload_bind()
        message = "DNS configuration applied"
        if not reload_result.get("skipped") and reload_result.get("returncode", 1) != 0:
            raise HTTPException(
                status_code=500,
                detail={"message": "Failed to reload BIND", "result": reload_result},
            )
        return ApplyResult(success=True, message=message, updated_at=datetime.utcnow())
    except HTTPException:
        raise
    except Exception as exc:  # pylint: disable=broad-except
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.post("/dns/reload")
async def reload_dns() -> Dict[str, Any]:
    result = agent.reload_bind()
    if not result.get("skipped") and result.get("returncode", 1) != 0:
        raise HTTPException(status_code=500, detail=result)
    return {"status": "success", "result": result}


@app.get("/dns/status")
async def dns_status() -> Dict[str, Any]:
    return {"status": "success", "result": agent.bind_status()}


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8082)
