import {
  AuthBackend,
  DNSRecord,
  DNSRecordType,
  DNSServer,
  DNSZone,
  DNSZoneType,
  DHCPHAMode,
  DHCPLease,
  DHCPLeaseState,
  DHCPOption,
  DHCPPool,
  DHCPReservation,
  DHCPServer,
  DHCPSubnet,
  DHCPSubnetType,
  FirewallAction,
  FirewallRule,
  Instance,
  InstanceStatus,
  LoginResponse,
  MailDomain,
  NATRule,
  NATType,
  QoSPolicy,
  RoutingRule,
  User,
  UserRole,
  VPNAuthType,
  VPNClient,
  VPNClientType,
  VPNProtocol,
  VPNProtocolRecommendation,
  VPNServer,
  VPNStatus,
} from '../../types'
import type { AuditLog, DashboardData, MetricSnapshot, NetworkInterface } from '../../types'
import type { MetricsOverview } from '../../hooks/useApi'

/**
 * Deterministic MSW fixture set for dev/test QA.
 *
 * Every id, name, and timestamp below is fixed so component tests, Playwright
 * e2e runs, and future todo tasks render identical data. Import from here in
 * handlers.ts (HTTP layer) and reuse directly in RTL/Playwright assertions.
 *
 * Instances (referenced throughout):
 *   1 = edge-berlin-01 (active)
 *   2 = edge-oslo-02   (maintenance)
 *   3 = edge-vie-03    (offline — never seen)
 */

export const FIXED_NOW = '2026-01-05T12:00:00.000Z'

export const adminUser: User = {
  id: 1,
  username: 'admin',
  email: 'admin@viswall.test',
  auth_backend: AuthBackend.LOCAL,
  role: UserRole.SUPERADMIN,
  is_active: true,
  instances: [1, 2, 3],
  preferences: {},
  last_login: FIXED_NOW,
  created_at: FIXED_NOW,
  updated_at: FIXED_NOW,
}

export const auditorUser: User = {
  id: 2,
  username: 'auditor',
  email: 'auditor@viswall.test',
  auth_backend: AuthBackend.LOCAL,
  role: UserRole.READONLY,
  is_active: true,
  instances: [],
  preferences: {},
  last_login: null,
  created_at: FIXED_NOW,
  updated_at: FIXED_NOW,
}

export const users: User[] = [adminUser, auditorUser]

/** Credentials accepted by the mocked POST /api/v1/auth/login handler. */
export const validCredentials = { username: 'admin', password: 'admin' } as const

export const loginResponse: LoginResponse = {
  access_token: 'e2e-test-token',
  token_type: 'bearer',
  user: adminUser,
}

/**
 * Instance fixture. The real InstanceStatus enum has no `offline` member, but
 * the UI badge layer (StatusBadge) renders `offline` for never-seen nodes, so
 * the fixture widens status to include it.
 */
export type InstanceFixture = Omit<Instance, 'status'> & {
  status: InstanceStatus | 'offline'
}

export const instances: InstanceFixture[] = [
  {
    id: 1,
    name: 'edge-berlin-01',
    hostname: 'berlin.edge.viswall.test',
    capabilities: ['firewall', 'vpn', 'dns', 'dhcp', 'mail'],
    api_endpoint: 'https://berlin.edge.viswall.test:8443/api',
    status: InstanceStatus.ACTIVE,
    last_seen: FIXED_NOW,
    config: {},
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
  {
    id: 2,
    name: 'edge-oslo-02',
    hostname: 'oslo.edge.viswall.test',
    capabilities: ['firewall', 'vpn'],
    api_endpoint: 'https://oslo.edge.viswall.test:8443/api',
    status: InstanceStatus.MAINTENANCE,
    last_seen: FIXED_NOW,
    config: {},
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
  {
    id: 3,
    name: 'edge-vie-03',
    hostname: 'vie.edge.viswall.test',
    capabilities: ['mail'],
    api_endpoint: 'https://vie.edge.viswall.test:8443/api',
    status: 'offline',
    last_seen: null,
    config: {},
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
]

export const metricsOverview: MetricsOverview = {
  instances: instances.length,
  active_instances: 1,
  firewall_rules: 3,
  mail_domains: 2,
  vpn_servers: 2,
}

export const dashboardData: DashboardData = {
  instance_id: 1,
  firewall_rule_count: 3,
  mail_domain_count: 2,
  vpn_server_count: 2,
  system: {
    cpu_percent: 23.5,
    memory_percent: 41.2,
    memory_used_bytes: 3_460_000_000,
    memory_total_bytes: 8_400_000_000,
    disk_percent: 38.0,
    disk_used_bytes: 96_000_000_000,
    disk_total_bytes: 256_000_000_000,
  },
  network: {
    interfaces: [
      { name: 'wan0', rx_bytes: 812_000_000, tx_bytes: 310_000_000 },
      { name: 'lan0', rx_bytes: 240_000_000, tx_bytes: 690_000_000 },
    ],
  },
  mail: {
    queue_size: 3,
    inbound_count: 128,
    outbound_count: 97,
    spam_count: 14,
    virus_count: 1,
  },
}

export const latestMetric: MetricSnapshot = {
  id: 1,
  instance_id: 1,
  timestamp: FIXED_NOW,
  cpu_percent: 23.5,
  memory_percent: 41.2,
  memory_used_bytes: 3_460_000_000,
  memory_total_bytes: 8_400_000_000,
  disk_percent: 38.0,
  disk_used_bytes: 96_000_000_000,
  disk_total_bytes: 256_000_000_000,
  interface_stats: [
    { name: 'wan0', rx_bytes: 812_000_000, tx_bytes: 310_000_000 },
    { name: 'lan0', rx_bytes: 240_000_000, tx_bytes: 690_000_000 },
  ],
  mail_queue_size: 3,
  mail_inbound_count: 128,
  mail_outbound_count: 97,
  mail_spam_count: 14,
  mail_virus_count: 1,
}

export const firewallRules: FirewallRule[] = [
  {
    id: 1,
    instance_id: 1,
    name: 'Allow HTTPS inbound',
    description: 'Public web traffic',
    enabled: true,
    source_type: 'any',
    source_value: null,
    dest_type: 'any',
    dest_value: null,
    service_protocol: 'tcp',
    service_ports: '443',
    action: FirewallAction.ACCEPT,
    log_enabled: false,
    order_index: 0,
    created_by: 1,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
  {
    id: 2,
    instance_id: 1,
    name: 'Allow DNS outbound',
    description: 'Resolver traffic to upstream',
    enabled: true,
    source_type: 'network',
    source_value: '192.168.1.0/24',
    dest_type: 'any',
    dest_value: null,
    service_protocol: 'udp',
    service_ports: '53',
    action: FirewallAction.ACCEPT,
    log_enabled: false,
    order_index: 1,
    created_by: 1,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
  {
    id: 3,
    instance_id: 1,
    name: 'Default drop',
    description: 'Catch-all',
    enabled: true,
    source_type: 'any',
    source_value: null,
    dest_type: 'any',
    dest_value: null,
    service_protocol: 'any',
    service_ports: null,
    action: FirewallAction.DROP,
    log_enabled: true,
    order_index: 2,
    created_by: 1,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
]

export const networkInterfaces: NetworkInterface[] = [
  {
    id: 1,
    instance_id: 1,
    name: 'wan0',
    type: 'physical',
    config_type: 'static',
    ip_address: '203.0.113.10',
    netmask: '255.255.255.0',
    gateway: '203.0.113.1',
    bandwidth_in: 500_000,
    bandwidth_out: 100_000,
    enabled: true,
    updated_at: FIXED_NOW,
  },
  {
    id: 2,
    instance_id: 1,
    name: 'lan0',
    type: 'physical',
    config_type: 'static',
    ip_address: '192.168.1.1',
    netmask: '255.255.255.0',
    gateway: null,
    bandwidth_in: null,
    bandwidth_out: null,
    enabled: true,
    updated_at: FIXED_NOW,
  },
]

export const natRules: NATRule[] = [
  {
    id: 1,
    instance_id: 1,
    name: 'LAN masquerade',
    description: 'Outbound NAT for LAN clients',
    enabled: true,
    type: NATType.MASQUERADE,
    interface: 'wan0',
    source_network: '192.168.1.0/24',
    dest_network: null,
    to_source: null,
    to_destination: null,
    service_protocol: null,
    service_ports: null,
    order_index: 0,
    created_by: 1,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
]

export const routingRules: RoutingRule[] = [
  {
    id: 1,
    instance_id: 1,
    name: 'VoIP via backup WAN',
    enabled: true,
    source_network: '192.168.1.0/24',
    service: 'sip',
    inbound_interface: 'lan0',
    gateway: '203.0.113.254',
    outbound_interface: 'wan1',
    mark: 10,
    order_index: 0,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
]

export const vpnServers: VPNServer[] = [
  {
    id: 1,
    instance_id: 1,
    name: 'wg-site-a',
    description: 'WireGuard site-to-site to Oslo',
    enabled: true,
    protocol: VPNProtocol.WIREGUARD,
    listen_address: '0.0.0.0',
    listen_port: 51820,
    network_cidr: '10.10.0.0/24',
    ipv6_tunnel_network: 'fd00:200::/64',
    dns_servers: ['192.168.1.1'],
    push_routes: ['10.20.0.0/24'],
    internet_redirect: false,
    status: VPNStatus.RUNNING,
    config: {},
    connected_clients: 2,
    bytes_received: 1_048_576,
    bytes_sent: 2_097_152,
    created_by: 1,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
  {
    id: 2,
    instance_id: 1,
    name: 'ovpn-roadwarrior',
    description: 'OpenVPN for remote users',
    enabled: true,
    protocol: VPNProtocol.OPENVPN,
    listen_address: '0.0.0.0',
    listen_port: 1194,
    network_cidr: '10.30.0.0/24',
    dns_servers: ['192.168.1.1'],
    push_routes: [],
    internet_redirect: true,
    status: VPNStatus.STOPPED,
    config: {},
    connected_clients: 0,
    bytes_received: 0,
    bytes_sent: 0,
    created_by: 1,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
]

export const vpnClients: VPNClient[] = [
  {
    id: 1,
    server_id: 1,
    user_id: 1,
    name: 'laptop-admin',
    description: 'Admin laptop',
    enabled: true,
    client_type: VPNClientType.USER,
    auth_type: VPNAuthType.PUBLIC_KEY,
    assigned_ip: '10.10.0.2',
    allowed_ips: ['10.10.0.2/32'],
    push_routes_override: [],
    last_connected: FIXED_NOW,
    last_ip: '198.51.100.23',
    connection_count: 42,
    bytes_received: 524_288,
    bytes_sent: 1_048_576,
    public_key: 'mock-public-key-laptop-admin',
    config_qr: null,
    config_file: null,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
  {
    id: 2,
    server_id: 1,
    user_id: null,
    name: 'oslo-site-peer',
    description: 'Site peer in Oslo',
    enabled: true,
    client_type: VPNClientType.SITE,
    auth_type: VPNAuthType.PSK,
    assigned_ip: '10.10.0.3',
    allowed_ips: ['10.10.0.3/32', '10.20.0.0/24'],
    push_routes_override: [],
    last_connected: FIXED_NOW,
    last_ip: '192.0.2.77',
    connection_count: 7,
    bytes_received: 524_288,
    bytes_sent: 1_048_576,
    public_key: 'mock-public-key-oslo-peer',
    config_qr: null,
    config_file: null,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
]

export const vpnProtocols: VPNProtocolRecommendation[] = [
  {
    protocol: VPNProtocol.WIREGUARD,
    priority: 1,
    security_score: 9,
    performance_score: 10,
    compatibility_score: 8,
    description: 'Modern, fast, minimal attack surface',
    use_cases: ['site-to-site', 'roadwarrior'],
  },
]

export const dnsServers: DNSServer[] = [
  {
    id: 1,
    instance_id: 1,
    name: 'bind-primary',
    description: 'Primary authoritative + recursive resolver',
    enabled: true,
    status: 'running',
    listening_addresses: ['192.168.1.1'],
    port: 53,
    is_recursive: true,
    is_authoritative: true,
    forwarders: ['9.9.9.9', '1.1.1.1'],
    allow_query: ['192.168.1.0/24'],
    allow_transfer: [],
    also_notify: [],
    dnssec_enabled: true,
    created_by: 1,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
    zones_count: 2,
  },
]

export const dnsZones: DNSZone[] = [
  {
    id: 1,
    server_id: 1,
    name: 'example.test',
    description: 'Internal forward zone',
    zone_type: DNSZoneType.MASTER,
    is_reverse: false,
    reverse_network: null,
    serial: 2026010501,
    refresh: 3600,
    retry: 600,
    expire: 604800,
    minimum_ttl: 300,
    enabled: true,
    master_server_address: null,
    forwarders: [],
    dnssec_enabled: true,
    dnssec_algorithm: 'ECDSAP256SHA256',
    dnssec_ds_record: null,
    created_by: 1,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
    records_count: 4,
  },
  {
    id: 2,
    server_id: 1,
    name: '1.168.192.in-addr.arpa',
    description: 'LAN reverse zone',
    zone_type: DNSZoneType.MASTER,
    is_reverse: true,
    reverse_network: '192.168.1.0/24',
    serial: 2026010501,
    refresh: 3600,
    retry: 600,
    expire: 604800,
    minimum_ttl: 300,
    enabled: true,
    master_server_address: null,
    forwarders: [],
    dnssec_enabled: false,
    dnssec_algorithm: 'ECDSAP256SHA256',
    dnssec_ds_record: null,
    created_by: 1,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
    records_count: 1,
  },
]

export const dnsRecords: DNSRecord[] = [
  {
    id: 1,
    zone_id: 1,
    name: '@',
    record_type: DNSRecordType.A,
    content: '192.168.1.1',
    ttl: 300,
    priority: 0,
    weight: 0,
    port: 0,
    flags: '',
    tag: null,
    comment: 'Apex',
    is_system: true,
    created_by: 1,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
  {
    id: 2,
    zone_id: 1,
    name: 'www',
    record_type: DNSRecordType.A,
    content: '192.168.1.10',
    ttl: 300,
    priority: 0,
    weight: 0,
    port: 0,
    flags: '',
    tag: null,
    comment: null,
    is_system: false,
    created_by: 1,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
  {
    id: 3,
    zone_id: 1,
    name: '@',
    record_type: DNSRecordType.MX,
    content: 'mail.example.test',
    ttl: 300,
    priority: 10,
    weight: 0,
    port: 0,
    flags: '',
    tag: null,
    comment: null,
    is_system: false,
    created_by: 1,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
  {
    id: 4,
    zone_id: 1,
    name: '@',
    record_type: DNSRecordType.TXT,
    content: 'v=spf1 mx -all',
    ttl: 300,
    priority: 0,
    weight: 0,
    port: 0,
    flags: '',
    tag: null,
    comment: null,
    is_system: false,
    created_by: 1,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
]

export const dhcpServers: DHCPServer[] = [
  {
    id: 1,
    instance_id: 1,
    name: 'kea-main',
    description: 'LAN Kea DHCPv4/v6 server',
    enabled: true,
    status: 'running',
    kea_ctrl_agent_address: '127.0.0.1',
    kea_ctrl_agent_port: 8000,
    ha_enabled: false,
    ha_mode: DHCPHAMode.HOT_STANDBY,
    ha_peer_address: null,
    dhcpv4_enabled: true,
    dhcpv6_enabled: false,
    created_by: 1,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
    subnets_count: 1,
  },
]

export const dhcpSubnets: DHCPSubnet[] = [
  {
    id: 1,
    server_id: 1,
    name: 'lan-v4',
    description: 'Main LAN subnet',
    subnet: '192.168.1.0/24',
    type: DHCPSubnetType.V4,
    interface: 'lan0',
    relay_addresses: [],
    domain_name: 'example.test',
    dns_servers: ['192.168.1.1'],
    ntp_servers: ['192.168.1.1'],
    routers: ['192.168.1.1'],
    lease_time_default: 3600,
    lease_time_max: 86400,
    lease_time_min: 300,
    delegated_prefix_length: null,
    enabled: true,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
    pools_count: 1,
    reservations_count: 1,
    leases_count: 2,
  },
]

export const dhcpPools: DHCPPool[] = [
  {
    id: 1,
    subnet_id: 1,
    start_address: '192.168.1.100',
    end_address: '192.168.1.199',
    type: DHCPSubnetType.V4,
    enabled: true,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
]

export const dhcpReservations: DHCPReservation[] = [
  {
    id: 1,
    subnet_id: 1,
    hostname: 'printer',
    ip_address: '192.168.1.50',
    hw_address: 'aa:bb:cc:00:11:50',
    type: DHCPSubnetType.V4,
    description: 'Office printer',
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
]

export const dhcpOptions: DHCPOption[] = [
  {
    id: 1,
    subnet_id: 1,
    option_code: 42,
    option_name: 'ntp-servers',
    option_value: '192.168.1.1',
    type: DHCPSubnetType.V4,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
]

export const dhcpLeases: DHCPLease[] = [
  {
    id: 1,
    subnet_id: 1,
    pool_id: 1,
    ip_address: '192.168.1.101',
    hw_address: 'aa:bb:cc:00:11:01',
    hostname: 'laptop-01',
    client_id: null,
    lease_start: FIXED_NOW,
    lease_end: '2026-01-05T13:00:00.000Z',
    released_at: null,
    state: DHCPLeaseState.ACTIVE,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
  {
    id: 2,
    subnet_id: 1,
    pool_id: 1,
    ip_address: '192.168.1.102',
    hw_address: 'aa:bb:cc:00:11:02',
    hostname: 'phone-02',
    client_id: null,
    lease_start: FIXED_NOW,
    lease_end: '2026-01-05T13:00:00.000Z',
    released_at: null,
    state: DHCPLeaseState.ACTIVE,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
]

export const mailDomains: MailDomain[] = [
  {
    id: 1,
    instance_id: 1,
    domain: 'example.test',
    enabled: true,
    spam_filter_enabled: true,
    virus_scan_enabled: true,
    dkim_enabled: true,
    dmarc_enabled: true,
    spf_enabled: true,
    llm_enabled: true,
    llm_config: {},
    groupware_enabled: true,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
  {
    id: 2,
    instance_id: 3,
    domain: 'legacy-mail.example',
    enabled: false,
    spam_filter_enabled: false,
    virus_scan_enabled: true,
    dkim_enabled: false,
    dmarc_enabled: false,
    spf_enabled: false,
    llm_enabled: false,
    llm_config: {},
    groupware_enabled: false,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
]

export const mailUsers = [
  {
    id: 1,
    domain_id: 1,
    username: 'admin',
    full_name: 'Admin User',
    quota_bytes: 1_073_741_824,
    quota_used: 104_857_600,
    enabled: true,
    forward_to: [],
    vacation_enabled: false,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
  {
    id: 2,
    domain_id: 1,
    username: 'support',
    full_name: 'Support Team',
    quota_bytes: 536_870_912,
    quota_used: 52_428_800,
    enabled: true,
    forward_to: ['forward@example.com'],
    vacation_enabled: false,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
]

export const mailMessages = [
  {
    id: 1,
    domain_id: 1,
    message_id: '<msg-001@example.test>',
    sender: 'newsletter@company.com',
    recipients: ['admin@example.test'],
    subject: 'Weekly Tech Newsletter #42',
    size_bytes: 45_000,
    body_preview: 'This week in tech news...',
    spam_score: 0.1,
    virus_status: 'clean',
    llm_category: 'newsletter',
    llm_confidence: 0.92,
    llm_reason: 'Newsletter pattern detected',
    llm_provider: 'openai',
    llm_model: 'gpt-4',
    classified_at: FIXED_NOW,
    action_taken: 'deliver',
    action_reason: null,
    action_taken_at: FIXED_NOW,
    action_taken_by: null,
    status: 'processed',
    received_at: FIXED_NOW,
  },
  {
    id: 2,
    domain_id: 1,
    message_id: '<msg-002@example.test>',
    sender: 'suspicious@phishing.net',
    recipients: ['admin@example.test'],
    subject: 'URGENT: Verify your account immediately',
    size_bytes: 12_000,
    body_preview: 'Your account has been compromised...',
    spam_score: 8.5,
    virus_status: 'clean',
    llm_category: 'phishing',
    llm_confidence: 0.97,
    llm_reason: 'Phishing indicators detected',
    llm_provider: 'openai',
    llm_model: 'gpt-4',
    classified_at: FIXED_NOW,
    action_taken: 'quarantine',
    action_reason: 'High spam score + phishing category',
    action_taken_at: FIXED_NOW,
    action_taken_by: null,
    status: 'quarantined',
    received_at: FIXED_NOW,
  },
]

export const qosPolicies: QoSPolicy[] = [
  {
    id: 1,
    instance_id: 1,
    name: 'wan-shaping',
    description: 'Shape wan0 to line rate',
    enabled: true,
    interface_name: 'wan0',
    interface_id: 1,
    algorithm: 'fq_codel',
    download_kbps: 500_000,
    upload_kbps: 100_000,
    applied: true,
    last_applied_at: FIXED_NOW,
    apply_error: null,
    classes: [
      {
        id: 1,
        policy_id: 1,
        name: 'voip',
        priority: 1,
        min_rate_kbps: 10_000,
        max_rate_kbps: 50_000,
        match_ports: [5060, 5061],
        match_dscp: 'ef',
        match_protocol: 'udp',
        created_at: FIXED_NOW,
        updated_at: FIXED_NOW,
      },
      {
        id: 2,
        policy_id: 1,
        name: 'bulk',
        priority: 9,
        min_rate_kbps: 1_000,
        max_rate_kbps: 400_000,
        match_ports: [],
        match_dscp: null,
        match_protocol: 'any',
        created_at: FIXED_NOW,
        updated_at: FIXED_NOW,
      },
    ],
    created_by: 1,
    created_at: FIXED_NOW,
    updated_at: FIXED_NOW,
  },
]

export const auditLogs: AuditLog[] = [
  {
    id: 3,
    user_id: 1,
    instance_id: 1,
    action: 'vpn.server.update',
    resource_type: 'vpn_server',
    resource_id: '1',
    old_value: { enabled: false },
    new_value: { enabled: true },
    ip_address: '192.168.1.10',
    timestamp: '2026-01-05T11:58:00.000Z',
  },
  {
    id: 2,
    user_id: 1,
    instance_id: 1,
    action: 'firewall.rule.create',
    resource_type: 'firewall_rule',
    resource_id: '3',
    old_value: null,
    new_value: { name: 'Default drop', action: 'drop' },
    ip_address: '192.168.1.10',
    timestamp: '2026-01-05T11:55:00.000Z',
  },
  {
    id: 1,
    user_id: 1,
    instance_id: null,
    action: 'auth.login',
    resource_type: 'user',
    resource_id: '1',
    old_value: null,
    new_value: null,
    ip_address: '192.168.1.10',
    timestamp: '2026-01-05T11:50:00.000Z',
  },
]
