"""Pure rendering of BIND9 configuration and zone files.

Split from file-system concerns: every function here takes typed payloads and
returns text, so rendering is unit-testable without I/O.
"""

from __future__ import annotations

import ipaddress
from typing import Collection

from viswall_dns_agent.payloads import DNSRecordPayload, DNSZonePayload, DNSServerConfigPayload

RNDC_KEY_INCLUDE = 'include "/etc/bind/rndc.key";'
# matches the key name in the distro-shipped /etc/bind/rndc.key
RNDC_KEY_NAME = "rndc-key"


def record_line(record: DNSRecordPayload) -> str:
    """Render one resource-record line; MX and SRV carry priority fields."""
    base = f"{record.name} {record.ttl} IN {record.record_type}"
    rtype = record.record_type.upper()
    if rtype == "MX":
        return f"{base} {record.priority} {record.content}"
    if rtype == "SRV":
        return f"{base} {record.priority} {record.weight} {record.port} {record.content}"
    return f"{base} {record.content}"


def default_soa(zone: DNSZonePayload) -> str:
    return (
        f"@ IN SOA ns1.{zone.name}. admin.{zone.name}. (\n"
        f"    {zone.serial} ; serial\n"
        f"    {zone.refresh} ; refresh\n"
        f"    {zone.retry} ; retry\n"
        f"    {zone.expire} ; expire\n"
        f"    {zone.minimum_ttl} ; minimum ttl\n"
        ")"
    )


def render_zone_text(zone: DNSZonePayload, include_dnssec: bool) -> str:
    """Render a master zone file body ($TTL, SOA, records, DNSSEC material)."""
    lines: list[str] = [f"$TTL {zone.minimum_ttl}"]

    has_soa = any(
        record.record_type.upper() == "SOA" for record in zone.records
    )
    if not has_soa:
        lines.append(default_soa(zone))

    lines.extend(record_line(record) for record in zone.records)

    if include_dnssec:
        for key in zone.dnssec_keys:
            if key.is_active and key.public_dnskey:
                lines.append(key.public_dnskey)
            if key.is_active and key.ds_record:
                lines.append(key.ds_record)

    return "\n".join(lines) + "\n"


def _acl(entries: Collection[str]) -> str:
    return "{ " + "; ".join(entries) + "; }" if entries else ""


def _listen_acl(addresses: Collection[str]) -> str:
    """Full braced ACL; a bare 0.0.0.0/:: is one address, not a wildcard."""
    if not addresses or any(addr in {"0.0.0.0", "::", "*"} for addr in addresses):
        return "{ any; }"
    return _acl(addresses)


def render_options_text(payload: DNSServerConfigPayload) -> str:
    """Render named.conf.options content: rndc controls plus the options block.

    Ubuntu's stock /etc/bind/named.conf includes this file for the options
    block only, so zone/key statements must never be emitted here (they go to
    named.conf.local) — a second options block would abort named at startup.
    """
    v4 = []
    v6 = []
    for addr in payload.listening_addresses:
        try:
            parsed = ipaddress.ip_address(addr.split("%")[0])
        except ValueError:
            continue
        (v6 if parsed.version == 6 else v4).append(addr)

    lines: list[str] = [
        "// Generated by Viswall DNS agent — options + rndc controls",
        RNDC_KEY_INCLUDE,
        f'controls {{ inet 127.0.0.1 port 953 allow {{ 127.0.0.1; }} keys {{ {RNDC_KEY_NAME}; }}; }};',
        "options {",
        '    directory "/var/cache/bind";',
    ]
    if v4:
        lines.append(f"    listen-on { _listen_acl(v4) };")
    if v6:
        lines.append(f"    listen-on-v6 { _listen_acl(v6) };")
    lines.append(f"    recursion {'yes' if payload.is_recursive else 'no'};")
    # distro default is dnssec-validation auto, which crash-loops named when
    # it cannot prime the root trust anchor (no outbound path)
    lines.append(f"    dnssec-validation {'auto' if payload.is_recursive else 'no'};")
    lines.append(f"    allow-query { _acl(payload.allow_query) };")
    lines.append(f"    allow-transfer { _acl(payload.allow_transfer) };")
    if payload.also_notify:
        # options-level also-notify applies to every master zone (BIND semantics)
        lines.append(f"    also-notify { _acl(payload.also_notify) };")
    if payload.forwarders:
        lines.append(f"    forwarders { _acl(payload.forwarders) };")
    lines.append("};")
    return "\n".join(lines) + "\n"


def render_zone_block(
    zone: DNSZonePayload, zone_file: str, tsig_key_name: str | None
) -> str:
    """Render one zone statement for named.conf.local."""
    if zone.zone_type == "master":
        allow_transfer = ""
        also_notify = ""
        if tsig_key_name:
            allow_transfer = f'    allow-transfer {{ key "{tsig_key_name}"; }};\n'
            also_notify = f'    also-notify {{ key "{tsig_key_name}"; }};\n'
        return (
            f'zone "{zone.name}" {{\n'
            "    type master;\n"
            f'    file "{zone_file}";\n'
            f"{allow_transfer}{also_notify}"
            "};\n"
        )
    if zone.zone_type == "slave":
        if not zone.master_server_address:
            raise ValueError(f"Slave zone {zone.name} missing master_server_address")
        master_clause = zone.master_server_address
        if tsig_key_name:
            master_clause = f"{zone.master_server_address} key {tsig_key_name}"
        return (
            f'zone "{zone.name}" {{\n'
            "    type slave;\n"
            f"    masters {{ {master_clause}; }};\n"
            f'    file "{zone_file}";\n'
            "};\n"
        )
    return (
        f'zone "{zone.name}" {{\n'
        f"    type {zone.zone_type};\n"
        f'    file "{zone_file}";\n'
        "};\n"
    )


def render_local_text(
    payload: DNSServerConfigPayload,
    zone_blocks: list[str],
) -> str:
    """Render named.conf.local content: TSIG keys plus zone statements."""
    tsig_blocks = [
        (
            f'key "{key.name}" {{\n'
            f"    algorithm {key.algorithm};\n"
            f'    secret "{key.secret}";\n'
            "};\n"
        )
        for key in payload.tsig_keys
        if key.is_active
    ]

    header = [
        "// Generated by Viswall DNS agent — zones + TSIG keys",
        f"// server_id={payload.server_id}",
    ]
    return "\n".join(header + ["", *tsig_blocks, *zone_blocks]) + "\n"
